### ISSUE TITLE
Versoin of  TensorFlow,Eigen3 and so on.

### ISSUE THREAD

**Issue by JensenGao** [lysuhin/tensorflow-object-detection-cpp#1]
I had built tensoflow c++ successfully, but when I run your pro, it gives lots of error. And I think maybe it is the problem of version of software. and I hope you can tell me what the version f yours. Thank you！

**Comment by JensenGao** [comment]
I have already dealt this problem, and thank you for you open source.

**Comment by lysukhin** [comment]
Hi, @JensenGao!
Sorry for my postponed answer, and I'm happy with your success! 
Thank you, too.
