### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by patrickjmccarty** [lysuhin/tensorflow-object-detection-cpp#10]
Can you please add a license to this project? I'm assuming you wrote all of the code here? Without a license, it currently can't be used as a starting point for other projects. I would appreciate if you chose a permissive, open source license like MIT, BSD 3-clause, or Apache 2.0. Thanks in advance!

If you need help understanding the terms of these licenses, I have found tl;dr Legal to be a good resource: https://tldrlegal.com/licenses/tags/Permissive

GitHub also has some help on choosing a license and licensing your repository:
https://help.github.com/en/articles/licensing-a-repository

**Comment by lysukhin** [comment]
MIT License added, sorry for delay.
