### ISSUE TITLE
fatal error: absl/strings/string_view.h

### ISSUE THREAD

**Issue by MickeyMouse2** [lysuhin/tensorflow-object-detection-cpp#5]
I installed all the dependencies. But in the end it’s such an error.
![screenshot from 2018-12-26 08-22-34](https://user-images.githubusercontent.com/38701425/50434798-71218300-08e7-11e9-9d21-606d1412ed8b.png)
cuda 9.0
cmake 3.12
ubuntu 16.04
i can`t understand what is it. Help

**Comment by zg9uagfv** [comment]
path: tensorflow/tensorflow/absl/strings/string_view.h

**Comment by 4saad** [comment]
i cant find absl directory in my tensorflow files

**Comment by JingyuQian** [comment]
@4saad [https://github.com/tensorflow/tensorflow/issues/22007#issuecomment-424553600](https://github.com/tensorflow/tensorflow/issues/22007#issuecomment-424553600) this solves the problem
