### ISSUE TITLE
The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by falithurrahman** [lysuhin/tensorflow-object-detection-cpp#7]
I followed all the step in this tutorial and when i tried to run ./tf_detector_example this error popped up. Is there any suggestion about what to do? thanks before
![screenshot from 2019-03-07 13-15-30](https://user-images.githubusercontent.com/32307731/53936085-4a4bae00-40db-11e9-8395-3950844efe9f.png)

**Comment by lysukhin** [comment]
Obviously, you should re-compile TF without AVX2 instructions.
